name: Update Mindmaps List

on:
  push:
    paths:
      - 'MapsCreated/**'

jobs:
  update-mindmaps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    
    - name: Update Mindmaps List
      run: |
        python3 -c "
import os
import json

# Get list of HTML files in MapsCreated directory
mindmap_files = [f for f in os.listdir('MapsCreated') if f.endswith('.html')]

# Read the current index.html
with open('index.html', 'r') as f:
    content = f.read()

# Create placeholder strings for files
files_list = ', '.join(f'"{file}"' for file in mindmap_files)
files_html_list = ''.join(f'<li><a href="MapsCreated/{file}">{file.replace(".html", "").replace("_", " ")}</a></li>\n' for file in mindmap_files)

# Replace placeholders
content = content.replace('<!-- MINDMAP_FILES_PLACEHOLDER -->', files_list)
content = content.replace('<!-- MINDMAP_LIST_PLACEHOLDER -->', files_html_list)

# Write updated content back to index.html
with open('index.html', 'w') as f:
    f.write(content)
"
    
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add index.html
        git commit -m "Update mindmaps list" || exit 0
        git push
